#############################################################################
# Makefile for building: QTSQLite.app/Contents/MacOS/QTSQLite
# Generated by qmake (2.01a) (Qt 4.8.6) on: Thu Oct 31 04:11:48 2013
# Project:  QTSQLite.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile QTSQLite.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/HEAD/mkspecs/unsupported/macx-clang -I. -I/usr/local/Cellar/qt/HEAD/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/HEAD/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/HEAD/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/HEAD/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/HEAD/lib/QtSql.framework/Versions/4/Headers -I/usr/local/Cellar/qt/HEAD/lib/QtSql.framework/Versions/4/Headers -I/usr/local/Cellar/qt/HEAD/include -I. -I. -I. -F/usr/local/Cellar/qt/HEAD/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/HEAD/lib -L/usr/local/Cellar/qt/HEAD/lib -framework QtSql -L/opt/X11/lib -L/usr/local/Cellar/qt/HEAD/lib -F/usr/local/Cellar/qt/HEAD/lib -framework QtCore -framework QtGui 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = HelloForm.cpp \
		main.cpp moc_HelloForm.cpp
OBJECTS       = HelloForm.o \
		main.o \
		moc_HelloForm.o
DIST          = /usr/local/Cellar/qt/HEAD/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/HEAD/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/include_source_dir.prf \
		QTSQLite.pro
QMAKE_TARGET  = QTSQLite
DESTDIR       = 
TARGET        = QTSQLite.app/Contents/MacOS/QTSQLite

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile QTSQLite.app/Contents/PkgInfo QTSQLite.app/Contents/Resources/empty.lproj QTSQLite.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_HelloForm.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) QTSQLite.app/Contents/MacOS/ || $(MKDIR) QTSQLite.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QTSQLite.pro  /usr/local/Cellar/qt/HEAD/mkspecs/unsupported/macx-clang/qmake.conf /usr/local/Cellar/qt/HEAD/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/HEAD/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/HEAD/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/HEAD/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/HEAD/lib/QtSql.framework/QtSql.prl \
		/usr/local/Cellar/qt/HEAD/lib/QtCore.framework/QtCore.prl \
		/usr/local/Cellar/qt/HEAD/lib/QtGui.framework/QtGui.prl
	$(QMAKE) -o Makefile QTSQLite.pro
/usr/local/Cellar/qt/HEAD/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/HEAD/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/HEAD/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/HEAD/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/HEAD/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/HEAD/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/HEAD/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/HEAD/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/release.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/HEAD/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/HEAD/lib/QtSql.framework/QtSql.prl:
/usr/local/Cellar/qt/HEAD/lib/QtCore.framework/QtCore.prl:
/usr/local/Cellar/qt/HEAD/lib/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile QTSQLite.pro

QTSQLite.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) QTSQLite.app/Contents || $(MKDIR) QTSQLite.app/Contents 
	@$(DEL_FILE) QTSQLite.app/Contents/PkgInfo
	@echo "APPL????" >QTSQLite.app/Contents/PkgInfo
QTSQLite.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) QTSQLite.app/Contents/Resources || $(MKDIR) QTSQLite.app/Contents/Resources 
	@touch QTSQLite.app/Contents/Resources/empty.lproj
	
QTSQLite.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) QTSQLite.app/Contents || $(MKDIR) QTSQLite.app/Contents 
	@$(DEL_FILE) QTSQLite.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,QTSQLite,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/HEAD/mkspecs/unsupported/macx-clang/Info.plist.app >QTSQLite.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/QTSQLite1.0.0 || $(MKDIR) .tmp/QTSQLite1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QTSQLite1.0.0/ && $(COPY_FILE) --parents HelloForm.h .tmp/QTSQLite1.0.0/ && $(COPY_FILE) --parents HelloForm.cpp main.cpp .tmp/QTSQLite1.0.0/ && $(COPY_FILE) --parents HelloForm.ui .tmp/QTSQLite1.0.0/ && (cd `dirname .tmp/QTSQLite1.0.0` && $(TAR) QTSQLite1.0.0.tar QTSQLite1.0.0 && $(COMPRESS) QTSQLite1.0.0.tar) && $(MOVE) `dirname .tmp/QTSQLite1.0.0`/QTSQLite1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QTSQLite1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r QTSQLite.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_HelloForm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_HelloForm.cpp
moc_HelloForm.cpp: ui_HelloForm.h \
		HelloForm.h
	/usr/local/Cellar/qt/HEAD/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ HelloForm.h -o moc_HelloForm.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_HelloForm.h
compiler_uic_clean:
	-$(DEL_FILE) ui_HelloForm.h
ui_HelloForm.h: HelloForm.ui
	/usr/local/Cellar/qt/HEAD/bin/uic HelloForm.ui -o ui_HelloForm.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

HelloForm.o: HelloForm.cpp HelloForm.h \
		ui_HelloForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HelloForm.o HelloForm.cpp

main.o: main.cpp HelloForm.h \
		ui_HelloForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_HelloForm.o: moc_HelloForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HelloForm.o moc_HelloForm.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

