######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 27 15:20:41 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += HelloForm.h
FORMS += HelloForm.ui
SOURCES += HelloForm.cpp main.cpp
QT += core gui sql
